### PR TITLE
feat(images): Update go versions for golang-tools

### PR DESCRIPTION
**Pull request by jhedev**
* Remove 1.10.2
* Add 1.10.3 and 1.10.4

### CODE REVIEW

**Review by philippfranke — APPROVED** [review]
👍

**Review by tobjaw — APPROVED** [review]
what's going on with packer 😨

**Comment by jhedev** [comment]
I have no idea :D

**Comment by jhedev** [comment]
Will take care of it later

**Comment by jhedev** [comment]
@tobjaw shouldn't this also only rebuild the ops-tools image and not **all** images?

**Pull request merged**
