### PR TITLE
feat: use ops-tools image for packer build

### PR DESCRIPTION
**Pull request by jhedev**
Let's see if this fixes the weird packer crash

### CODE REVIEW

**Comment by jhedev** [comment]
somehow packer can't connect to the instance... not sure why. Switched to a different instance type to see if that helps

**Comment by jhedev** [comment]
Previously packer just crashed (probably due to the same issue) and we were using the `packer:light` docker image which uses the latest version of packer.

**Comment by jhedev** [comment]
Regarding the packer crash see https://github.com/hashicorp/packer/issues/6707 and https://github.com/hashicorp/packer/issues/6696

tl;dr: there are regressions in packer 1.3.0

**Comment by jhedev** [comment]
@philippfranke FIXED!

**Review by philippfranke — APPROVED** [review]
👍

**Pull request merged**
